### ISSUE TITLE
Excel export not working

### ISSUE THREAD

**Issue by thgoebel** [tanzquotient/tq_website#250]
To reproduce:

1. Register for a course
2. Click _redeem voucher_
3. Enter code + click _Pay with voucher_
4. Grab crash log

```
[21/Feb/2020 06:38:59] ERROR [django.request:228] Internal Server Error: /de/auth/coursepayment/1017/export/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/webapps/tq_website/payment/views.py", line 166, in dispatch
    return super(TeacherOfCourseOnly, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/webapps/tq_website/payment/views.py", line 271, in get
    return services.export_subscriptions([kwargs.get('course', None)], 'xlsx')
  File "/webapps/tq_website/courses/services.py", line 619, in export_subscriptions
    return export(export_format, title='Kursteilnehmer-{}'.format(course_name), data=export_data[0]['data'])
  File "/webapps/tq_website/courses/utils/export_files/export.py", line 6, in export
    return export_excel(title=title, multiple=multiple, data=data)
  File "/webapps/tq_website/courses/utils/export_files/export_excel.py", line 17, in export_excel
    sheets = {workbook.get_active_sheet(): data}
AttributeError: 'Workbook' object has no attribute 'get_active_sheet'
```

**Comment by DanielSparber** [comment]
The error seems to be unrelated to vouchers

**Comment by thgoebel** [comment]
Okay, but it does prevent me from paying with a voucher :)
Thanks for fixing it so quickly!

**Comment by DanielSparber** [comment]
It is not related at all to vouchers. However, I saw another error in the logs that is ;)
